<center><img src="https://gitlab.com/accredian/insaid-data/-/raw/main/Logo-Accredian/Case-Study-Cropped.png" width= 30% /></center>

**<center><h3>Scientific Exploration of Industry Data Assignment (Solution)</h3></center>**

---
# **Table of Contents**
---

**1.** [**Problem Statement**](#Section1)<br>
**2.** [**Objective**](#Section2)<br>
**3.** [**Installing & Importing Libraries**](#Section3)<br>
  - **3.1** [**Installing Libraries**](#Section31)
  - **3.2** [**Upgrading Libraries**](#Section32)
  - **3.3** [**Importing Libraries**](#Section33)

**4.** [**Data Acquisition & Description**](#Section4)<br>
  - **4.1** [**Data Description**](#Section41)<br>

**5.** [**Data Pre-Profiling**](#Section5)<br>
**6.** [**Data Cleaning**](#Section6)<br>
**7.** [**Data Post-Profiling**](#Section7)<br>
**8.** [**Exploratory Data Analysis**](#Section8)<br>
**9.** [**Conclusion**](#Section9)<br>

---
<a name = Section1></a>
# **1. Problem Statement**
---

- There are **17 penguin species** on the planet, but the eight most iconic reside in **Antarctica**, its nearby islands, and the **sub-Antarctic** archipelagos of **South Georgia** and the **Falklands**.

- You are a data scientist at the **Palmer Station, Antarctica LTER**, a member of the Long Term Ecological Research Network.

<center><img src="https://raw.githubusercontent.com/HirenRupchandani/Credit-Management-System/master/lter_penguins.png" height=300></center>

- You are given a dataset on 3 types of penguins i.e. **Adelie**, **Gentoo** & **Chinstrap** from 3 islands in the Palmer Archipelago, Antarctica, and the features that describe them.

---
<a name = Section2></a>
# **2. Objective**
---

- The objective of this assignment is to **perform analysis** on the **Palmer Archipelago penguins** dataset.

---
<a name = Section3></a>
# **3. Installing & Importing Libraries**
---

<a name = Section31></a>
### **3.1 Installing Libraries**

In [ ]:
!pip install -q datascience                                                       # Package that is required by pandas profiling
!pip install -q pandas-profiling

     |████████████████████████████████| 71kB 5.2MB/s
  Building wheel for folium (setup.py) ... done

<a name = Section32></a>
### **3.2 Upgrading Libraries**

- **After upgrading** the libraries, you need to **restart the runtime** to make the libraries in sync.

- Make sure not to execute the cell above (3.1) and below (3.2) again after restarting the runtime.

In [ ]:
!pip install -q --upgrade pandas-profiling

     |████████████████████████████████| 256kB 7.2MB/s
     |████████████████████████████████| 112kB 17.6MB/s
     |████████████████████████████████| 1.1MB 13.6MB/s
     |████████████████████████████████| 645kB 27.9MB/s
     |████████████████████████████████| 61kB 7.4MB/s
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/tangled-up-in-unicode/
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /packages/93/3e/cb354fb2097fcf2fd5b5a342b10ae2a6e9363ba435b64e3e00c414064bc7/tangled_up_in_unicode-0.1.0-py3-none-any.whl
     |████████████████████████████████| 3.1MB 5.8MB/s
     |████████████████████████████████| 81kB 11.1MB/s
     |████████████████████████████████| 10.1MB 21.9MB/s
     |████████████████████████████████| 296kB 43.7MB/s
  Building wheel for phik (setup.py) ... done
  Building wheel for htmlmin (setup.py) ... done
ERROR: google-colab 1.0.0 has requirement requests~=2.23.0, but you'll have requests 2.25.1 which is incompatible.
ERROR: phik 0.11.2 has requirement scipy>=1.5.2, but you'll have scipy 1.4.1 which is incompatible.

<a name = Section33></a>
### **3.3 Importing Libraries**

In [ ]:
#-------------------------------------------------------------------------------------------------------------------------------
import pandas as pd                                                 # Importing for panel data analysis
from pandas_profiling import ProfileReport                          # Importing Pandas Profiling (To generate Univariate Analysis)
pd.set_option('display.max_columns', None)                          # Unfolding hidden features if the cardinality is high
pd.set_option('display.max_colwidth', None)                         # Unfolding the max feature width for better clearity
pd.set_option('display.max_rows', None)                             # Unfolding hidden data points if the cardinality is high
pd.set_option('mode.chained_assignment', None)                      # Removing restriction over chained assignments operations
pd.set_option('display.float_format', lambda x: '%.5f' % x)         # To suppress scientific notation over exponential values
#-------------------------------------------------------------------------------------------------------------------------------
import numpy as np                                                  # Importing package numpys (For Numerical Python)
#-------------------------------------------------------------------------------------------------------------------------------
import matplotlib.pyplot as plt                                     # Importing pyplot interface of matplotlib
import seaborn as sns                                               # Importing seaborn library for interactive visualization
%matplotlib inline
#-------------------------------------------------------------------------------------------------------------------------------
import warnings                                                     # Importing warning to disable runtime warnings
warnings.filterwarnings("ignore")                                   # Warnings will appear only once

---
<a name = Section4></a>
# **4. Data Acquisition & Description**
---

- The data was **collected** and made **available** by **Dr. Kristen Gorman** and the **Palmer Station, Antarctica LTER**.

- The dataset is a great **alternative** to the **iris dataset**.

</br>

| Records | Features | Dataset Size |
| :-- | :-- | :-- |
| 344 | 7 | 15.0 KB |

</br>

|Id|Feature|Description|
|:--|:--|:--|
|01|**species**| Penguin species (Chinstrap, Adélie, or Gentoo).|
|02|**island**| Island where the penguin is found.|
|03|**culmen_length_mm**| Length of upper ridge of beak of the penguin (in mm).|
|04|**culmen_depth_mm**| Depth of the beak of the penguin (in mm).|
|05|**flipper_length_mm**| Length of the flipper of the penguin (in mm).|
|06|**body_mass_g**| Weight of the penguin (in grams).|
|07|**sex**| Gender of the penguin.|

In [ ]:
data = pd.read_csv(filepath_or_buffer="https://raw.githubusercontent.com/insaid2018/PGPDSAI/main/03%20Term%203%20-%20EDA%20%26%20Data%20Storytelling/03%20Module%203/data/penguins.csv")
print('Data Shape:', data.shape)
data.head()

Data Shape: (344, 7)

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10000,18.70000,181.00000,3750.00000,MALE
1,Adelie,Torgersen,39.50000,17.40000,186.00000,3800.00000,FEMALE
2,Adelie,Torgersen,40.30000,18.00000,195.00000,3250.00000,FEMALE
3,Adelie,Torgersen,nan,nan,nan,nan,NaN
4,Adelie,Torgersen,36.70000,19.30000,193.00000,3450.00000,FEMALE

<a name = Section41></a>
### **4.1 Data Description**

- In this section we will get **description** and **statistics** about the data.

In [ ]:
data.describe()

       culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
count         342.00000        342.00000          342.00000    342.00000
mean           43.92193         17.15117          200.91520   4201.75439
std             5.45958          1.97479           14.06171    801.95454
min            32.10000         13.10000          172.00000   2700.00000
25%            39.22500         15.60000          190.00000   3550.00000
50%            44.45000         17.30000          197.00000   4050.00000
75%            48.50000         18.70000          213.00000   4750.00000
max            59.60000         21.50000          231.00000   6300.00000

**Observations**:

<a name = Section42></a>
### **4.2 Data Information**

 - In this section, we will get **information about the data** and see some observations.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   culmen_length_mm   342 non-null    float64
 3   culmen_depth_mm    342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

**Observations**:

---
<a name = Section5></a>
# **5. Data Pre-Profiling**
---

- For a quick analysis, we will generate a HTML using pandas profiling.

In [ ]:
# profile = ProfileReport(df=data)
# profile.to_file(output_file='Pre Profiling Report.html')
# print('Accomplished!')

**Observations**:

---
<a name = Section6></a>
# **6. Data Cleaning**
---

- We will now clean our data by filling in the missing data.

---
**<h4>Question 1:** Create a function that replaces the null values with the appropriate values.</h4>

---

<details>

**<summary>Hint:</summary>**

- Use .isna().sum() to check for number of null values in the dataset.

- Replace continuous features' missing values with the mean of that feature.

- For categorical features, use mode of that feature to fill in missing values.

- Use .fillna() method to fill in the null values in the dataset.

</details>

In [ ]:
def fill_null_values(data=None):

  # Write your code here

- We have **successfully cleaned** our data.

---
<a name = Section7></a>
# **7. Data Post-Profiling**
---

In [ ]:
# profile = ProfileReport(df=data)
# profile.to_file(output_file='Post Profiling Report.html')
# print('Accomplished!')

**Observations**:

---
<a name = Section8></a>
# **8. Exploratory Data Analysis**
---

---
**<h4>Question 2:** Create a function that displays the frequency & proportion of each species of penguins in the dataset.</h4>

---

<details>

**<summary>Hint:</summary>**

- You can use a countplot to plot the count for each species.

- Set the figure size as 7 x 7 inches

- Set x, y labels of size 14, ticks of size 12 and title label of size 16.

- Beautify the plot to make it look appealing.

</details>

In [ ]:
def species_counter(data=None):

  # Write your code here

**Observations**:

---
**<h4>Question 3:** Create a function that displays the proportion of penguins across all the islands.</h4>

---

<details>

**<summary>Hint:</summary>**

- Use .value_counts() method to calculate the penguin frequency for each island.

- You can then use a .plot.pie() method to plot the proportion for each island.

- Set the figure size as 7 x 7 inches

- Beautify the plot to make it look appealing.

</details>

In [ ]:
def island_counter(data=None):

  # Write your code here

**Observations**:

---
**<h4>Question 4:** Create a function that displays the frequency of each penguin species across all the islands in the dataset.</h4>

---

<details>

**<summary>Hint:</summary>**

- You can use the .countplot() method to plot the frequency for each species across all the islands.

- Keep x parameter as island

- You can use the hue parameter for species.

- Set the figure size as 7 x 7 inches

- Set x, y labels of size 14, ticks of size 12 and title label of size 16.

- Beautify the plot to make it look appealing.

</details>

In [ ]:
def species_island_counter(data=None):

  # Write your code here

**Observations**:

---
**<h4>Question 5:** Create a function that displays the frequency of penguins and their genders.</h4>

---

<details>

**<summary>Hint:</summary>**

- You can use the .countplot() method to plot the frequency for each species across all the islands.

- Keep x parameter as species

- You can use the hue parameter as sex.

- Set the figure size as 7 x 7 inches

- Set x, y labels of size 14, ticks of size 12 and title label of size 16.

- Beautify the plot to make it look appealing.

</details>

In [ ]:
def count_gender(data=None):

  # Write your code here

**Observations**:

---
**<h4>Question 6:** Create a function compares the body mass across species.<br></h4>

---

<details>

**<summary>Hint:</summary>**

- You can plot a boxplot to compare the body masses of each species in the dataset.

- Use sns.boxplot() with x='species' and y='body_mass_g' to obtain the required plot.

- Set the figure size as 7 x 7 inches

- Set x, y labels of size 14, ticks of size 12 and title label of size 16.

- Beautify the plot to make it look appealing.

</details>

In [ ]:
def species_body_mass(data=None):

  # Write your code here

**Observations**:

---
**<h4>Question 7:** Create a function that compares the flipper length of different species.</h4>

---

<details>

**<summary>Hint:</summary>**

- You can plot a kde plot to compare the flipper length of each species.

- Use sns.kdeplot() with species as hue and x='flipper_length_mm' to obtain the required plot.

- Set the figure size as 10 x 7 inches

- Set x, y labels of size 14, ticks of size 12 and title label of size 16.

- Beautify the plot to make it look appealing.

</details>

In [ ]:
def flipper_comparison(data=None):

  # Write your code here

**Observations**:

---
**<h4>Question 8:** Create a function to get a clear grouping of the species concerning culmen features of the penguins.</h4>

---

<details>

**<summary>Hint:</summary>**

- You can plot a scatterplot of culmen_length_mm against culmen_depth_mm, keeping species as hue.

- Set the figure size as 15 x 7 inches

- Set x, y labels of size 14, ticks of size 12 and title label of size 16.

- Beautify the plot to make it look appealing.

In [ ]:
def culmen_features(data=None):

  # Write your code here

**Observations**:

---
**<h4>Question 9:** Create a function that shows species grouped concerning culmen length and flipper length of the penguins.</h4>

---

<details>

**<summary>Hint:</summary>**

- You can plot a scatterplot of culmen_depth_mm against flipper_length_mm, keeping species as hue.

- Set the figure size as 15 x 7 inches.

- Set x, y labels of size 14, ticks of size 12 and title label of size 16.

- Beautify the plot to make it look appealing.

In [ ]:
def culmen_vs_flipper(data=None):

  # Write your code here

**Observations**:

---
**<h4>Question 10:** Create a function that shows species & sex grouped concerning body mass and flipper length of the penguins.</h4>

---

<details>

**<summary>Hint:</summary>**

- You can plot a scatterplot of body_mass_g against flipper_length_mm, keeping species as hue.

- You can introduce 'style' parameter to distinguish between both the sexes.

- Set the figure size as 15 x 7 inches

- Set x, y labels of size 14, ticks of size 12 and title label of size 16.

- Beautify the plot to make it look appealing.

In [ ]:
def mass_vs_flipper(data=None):

  # Write your code here

**Observations**:

---
**<h4>Question 11:** Create a function that returns a dataframe consisting of only Adelie penguins.</h4>

---

<details>

**<summary>Hint:</summary>**

- Use **data['species']=='Adelie'** as the condition to create a new dataframe named 'adelie'.

In [ ]:
def adelie_penguins(data=None):

  # Write your code here

---
**<h4>Question 12:** Create a function that compares the various features of the adelie penguins.</h4>

---

<details>

**<summary>Hint:</summary>**

- Use a pairplot to compare culmen length, depth, flipper length, body mass, and the residing island of the Adelie penguins.

- Create a figure of appropriate size using the sns.pairplot() method

- Use markers to easily distinguish hues.

In [ ]:
def adelie_fetures(data=None):

  # Write your code here

**Observations**:

---
<a name = Section9></a>
# **9. Conclusion**
---